project:
  type: website
  output-dir: docs

website:
  title: "About JinRui"
  favicon: favicon.png
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: About me
      - href: projects.qmd
        text: projects
      - href: hobbies.qmd
        text: My Hobbies
      - href: reflections.qmd
        text: GenAI Reflections
format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left


